import { ComingSoon } from "@components/Home/ComingSoon";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>TournaMate App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ComingSoon/>
    </>
  );
};

export default Home;

