import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useAuth, UserButton } from "@clerk/nextjs";


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>TournaMate App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
        <span className="text-[#2196F3]">Tourna</span>
        <span className="text-[#F24E1E]">Mate</span> App
        </h1>
        <AuthShowcase />
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const {isSignedIn, userId} = useAuth();
  return (
    <div className="flex flex-col items-center justify-center gap-2">
      {isSignedIn && (
        <div className="flex flex-col">
          <div className="flex flex-row">
            <p className="text-2xl text-blue-500">Logged in as {userId}</p>
            <UserButton />
          </div>
          <div className="flex space-x-4 justify-center pt-2">
            <Link
              className="rounded-md border border-black bg-violet-50 p-2 text-xl shadow-lg hover:bg-violet-100"
              href={"./dashboard"}
            >
              To Application
            </Link>
          </div>
        </div>
      )}
      {!isSignedIn && (
        <p className="text-center text-2xl">
          <Link href="/sign-in">Sign In</Link>
        </p>
      )}
    </div>
  );
};