import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useAuth, UserButton, useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>TournaMate App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-full flex-col items-center justify-between p-4 bg-home-mobile lg:bg-home-desktop lg:bg-cover bg-right-bottom">
        <h1 className="lg:mt-80 mt-24 font-extrabold leading-normal text-gray-700 text-5xl text-center lg:text-8xl">
          <span className="text-[#2196F3]">Tourna</span>
          <span className="text-[#F24E1E]">Mate</span> App
        </h1>
        <div className="lg:mb-28 mb-8">
          <AuthShowcase />
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { isSignedIn } = useAuth();
  const { user } = useUser();

  return (
    <div className="flex flex-col items-center justify-center gap-2">
      {isSignedIn && (
        <div className="flex flex-col gap-4">
          <div className="flex flex-row">
            <p className="lg:text-5xl text-2xl font-semibold text-[#F24E1E]">
              Welcome {user?.fullName}!
            </p>
          </div>
          <div className="rounded-xl bg-green-500/90 p-4 text-center text-xl lg:text-5xl font-semibold tracking-wide text-white">
            <Link href={"./dashboard"}>To Application</Link>
          </div>
        </div>
      )}
      {!isSignedIn && (
        <p className="rounded-xl bg-green-500/90 p-4 text-center text-5xl font-semibold tracking-wide text-white">
          <Link href="/sign-in">Sign in</Link>
        </p>
      )}
    </div>
  );
};
